site_name: Why cannot you set up Xdebug?
site_author: Paul Radley
site_description: Personal Blog
site_dir: build
site_url: https://paulradley.github.com/why-cannot-you-set-up-xdebug
repo_url: https://github.com/paulradley/why-cannot-you-set-up-xdebug

theme:
  name: material
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.follow

plugins:
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list

extra_css:
  - assets/extra.css

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTIC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

nav:
  - Why cannot you set up Xdebug?: index.md